
server:
  port: 8091
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100



spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/e_ticketing
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    url: jdbc:postgresql://0.0.0.0:5432/e_ticketing
    user: postgres
    password: admin
    locations: classpath:/db/migration
    baseline-on-migrate: true
    level:
      org.flywaydb: DEBUG

#debug: true

# Optional: Enable more logging (if using MyBatis or JPA logs)
# logging:
#   level:
#     org.mybatis: DEBUG
#     org.hibernate.SQL: DEBUG
#     org.hibernate.type.descriptor.sql: TRACE
